dictation_peek: fix fallback when disabled (#52)
#47 updates the callsites where the setting is enabled, but not the
callsite where the setting is turned off.

```
2023-04-16 08:56:06    IO TypeError while querying accessibility for context-aware dictation: 'dictation_peek() missing 2 required positional arguments: 'left' and 'right'':
2023-04-16 08:56:06    IO Traceback (most recent call last):
2023-04-16 08:56:06    IO   File "/Users/phillco/.talon/user/talon-axkit/dictation/dictation_context.py", line 121, in dictation_peek
    return actions.next()
2023-04-16 08:56:06    IO   File "talon/scripting/actions.py", line 88, in __call__
2023-04-16 08:56:06    IO TypeError: dictation_peek() missing 2 required positional arguments: 'left' and 'right'
```